package it.polimi.ingsw.network.socketMiddleware;

public enum Action {
    CLIENT_REGISTRATION, CHANGE_TURN, USER_INSERTION, SEND_PRIVATE_MESSAGE, SEND_BROADCAST_MESSAGE, ADD_PLAYER, CHOOSE_NUMBER_OF_PLAYERS
}
